///@package io.alkapivo.visu.ui

///@type {Map<String, Callable>}
global.__VisuStyles = new Map(String, Callable, {
  "menu-title": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.CENTER },
      font: "font_kodeo_mono_28_bold",
      color: VETheme.color.text,
      enableColorWrite: false,
    },
  },
  "menu-button-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.CENTER },
      font: "font_kodeo_mono_18_bold",
      color: VETheme.color.text,
      //offset: { x: 24 },
      enableColorWrite: false,
      colorHoverOver: VETheme.color.accentLight,
      colorHoverOut: VETheme.color.sideDark,
      //backgroundColor: VETheme.color.side,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
      backgroundAlpha: 0.75,
    },
  },
  "menu-label-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.CENTER },
      font: "font_kodeo_mono_18_bold",
      color: VETheme.color.text,
      //offset: { x: 24 },
      enableColorWrite: false,
      //backgroundColor: VETheme.color.side,
      colorHoverOver: VETheme.color.accentLight,
      colorHoverOut: VETheme.color.accentShadow,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
      backgroundAlpha: 0.01,
    },
  },
  "menu-button-input-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.LEFT },
      font: "font_kodeo_mono_18_bold",
      color: VETheme.color.text,
      outline: true,
      outlineColor: VETheme.color.side,
      offset: { x: 24 },
      enableColorWrite: false,
      //colorHoverOver: VETheme.color.accentLight,
      //colorHoverOut: VETheme.color.sideDark,
      //backgroundColor: VETheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
    },
    input: {
      label: {
        align: { v: VAlign.CENTER, h: HAlign.CENTER },
        font: "font_kodeo_mono_18_bold",
        color: VETheme.color.textFocus,
        enableColorWrite: false,
        colorHoverOver: VETheme.color.accentLight,
        colorHoverOut: VETheme.color.sideDark,
        //backgroundColor: VETheme.color.side,
        backgroundAlpha: 0.75,
        backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
      },
      colorHoverOver: VETheme.color.accentLight,
      colorHoverOut: VETheme.color.sideDark,
      //backgroundColor: VETheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
    },
  },
  "menu-spin-select-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.LEFT },
      font: "font_kodeo_mono_18_bold",
      color: VETheme.color.text,
      outline: true,
      outlineColor: VETheme.color.side,
      offset: { x: 24 },
      useScaleWithOffset: true,
      enableColorWrite: false,
      //colorHoverOver: VETheme.color.accentLight,
      //colorHoverOut: VETheme.color.sideDark,
      //backgroundColor: VETheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
    },
    previous: {
      sprite: {
        name: "texture_menu_button_previous",
        blend: VETheme.color.textFocus,
      },
      colorHoverOver: VETheme.color.accentLight,
      colorHoverOut: VETheme.color.sideDark,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 3 },
    },
    preview: {
      label: {
        align: { v: VAlign.CENTER, h: HAlign.CENTER },
        font: "font_kodeo_mono_18_bold",
        color: VETheme.color.textFocus,
        enableColorWrite: false,
      },
      colorHoverOver: VETheme.color.accentLight,
      colorHoverOut: VETheme.color.sideDark,
      backgroundMargin: { top: 6, left: 3, bottom: 6, right: 3 },
      backgroundAlpha: 0.75,
    },
    next: {
      sprite: {
        name: "texture_menu_button_next",
        blend: VETheme.color.textFocus,
      },
      colorHoverOver: VETheme.color.accentLight,
      colorHoverOut: VETheme.color.sideDark,
      backgroundMargin: { top: 6, left: 3, bottom: 6, right: 6 },
      backgroundAlpha: 0.75,
    },
  },
  "menu-keyboard-key-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.LEFT },
      font: "font_kodeo_mono_18_bold",
      color: VETheme.color.text,
      offset: { x: 24 },
      useScaleWithOffset: true,
      enableColorWrite: false,
      outline: true,
      outlineColor: VETheme.color.side,
      //colorHoverOver: VETheme.color.accentLight,
      //colorHoverOut: VETheme.color.sideDark,
      //backgroundColor: VETheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
    },
    preview: {
      align: { v: VAlign.CENTER, h: HAlign.CENTER },
      font: "font_kodeo_mono_18_bold",
      color: VETheme.color.textFocus,
      enableColorWrite: false,
      colorHoverOver: VETheme.color.accentLight,
      colorHoverOut: VETheme.color.sideDark,
      //backgroundColor: VETheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
    }
  },
})
#macro VisuStyles global.__VisuStyles